# Welcome to Jekyll!

# Website settings
title: Dhanashri
description: This is my personal websit
keywords: Dhanshri,dhanshri, python, java,Palokdar, go, developer,
baseurl:  /dpalodkar # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://DhanashriPalodkar.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
#url: http://127.0.0.1:4000
img_path: /dpalodkar/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Dhanashri  # Be used at blog posts' author.
  first_name: Dhanashri  # Be used at index page about me section.
  last_name: palodkar  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: DhanashriPalodkar  # Leave blank if you don't have now
  linkedin_id: dhanashripalodkar # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username: d_palodkar  # Leave blank if you don't have now
  email: dpalodkar14@gmail.com # Leave blank if you don't have now
  cv:  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: I am a recent graduate from northeastern university and worked as interns at Redhat and MIT media labs. I am a software engineer experienced with end-to-end software development cycle from requiremnet gathering to communicating with clients. I enjoy working in newly emeriging tech and buisness and product side of tech development. Tennis,glof and painting are some of the other activities I do apart from tech and always seeking opportunity to learn new opportunities .  # Describe yourself.

# comment
#disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  #name: jalpc

# analytics
## google analytics
# ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
#   id: G-1NX2DWWGGH

# ## google optimize
# go:
#   # id:

# ## growingIO
# gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
#   # id:

# ## donation
# donation: off  # type 'on'/'off' to choice display donation button at post page or not

# ## carousels
# index_carousel: on  # index page carousel switch
# blog_carousel: on  # blog page carousel switch

# # scss
# sass:
#   style: compressed

# # Build settings
# encoding: utf-8

# # other settings
# highlighter: rouge
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

